- name: varaiables from files
  hosts: web
  vars_files:
  - variables.yaml
  tasks: 
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer{{Trainer}}, Duration is {{Duration}}"