- name: variables
  hosts: web
  vars: #variable declaration
    Course: "AWS"
    Trainer: "Nikhil"
    Duration: "120hrs"
  tasks: 
  - name: print info
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from  Trainer {{Trainer}} Duration is {{Duration}}"